### PR TITLE
sponsor: use Sopra-Steria logo provided by them

### PR DESCRIPTION
**Pull request by clacote**
Use logo provided by `xxx@soprasteria.com` on 03-27.

### CODE REVIEW

**Comment by sdeleuze** [comment]
That's the former logo we used that was displayed so small that we dot really see it. Do we really want to integrate this ? If that's what we want, let's at least crop it to optimize the size of the displayed logo.

**Comment by clacote** [comment]
That's what THEY want:
> Je me permets de vous contacter suite à l’affichage des logos sur votre site. Celui pour Sopra Steria n’est pas le bon, je vous joint donc le logo que nous utilisons.

**Comment by sdeleuze** [comment]
Ok

**Comment by sdeleuze** [comment]
Logo cropped https://github.com/mixitconf/mixit/commit/8c683ca101eee987f661a961bfafa4d63b0ac7cf

**Comment by clacote** [comment]
@doublejess hates that we crop their logo. It's not hers, but maybe it's a designer thing to not crop.

**Comment by sdeleuze** [comment]
I am pretty sure she will be ok with this transparency crop that ensure more consistency accross logos ;-)

**Pull request merged**
