### PR TITLE
 Adds features to be able to logout and login via a token to the app

### PR DESCRIPTION
**Pull request by javamind**

### CODE REVIEW

**Comment by javamind** [comment]
WIP

**Comment by sdeleuze** [comment]
@javamind What about `ServerRequest#session()` or if you want direct cookie access `ServerRequest.cookies()` ?

**Comment by javamind** [comment]
@sdeleuze I tried to add an element in the map of the cookies (included in ServerRequest) but this map is unmodifiable. For me it's logic. It just lacks access to populate cookies in response

**Comment by sdeleuze** [comment]
@javamind It seems this is maybe not exposed yet in functional WebFlux API, I have created https://jira.spring.io/browse/SPR-16121.

**Comment by javamind** [comment]
Thanks.

**Comment by sdeleuze** [comment]
@javamind https://jira.spring.io/browse/SPR-16121 will be part of Spring Framework 5.0.2

Session attributes seems to be already usable via [`ServerRequest.session()`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/reactive/function/server/ServerRequest.html#session--) (the map is mutable).

**Comment by javamind** [comment]
yep cool

**Pull request merged**
